server:
  port: 9000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://ibk-discover-service:8761/eureka/

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account/**

        - id: transfer-service
          uri: lb://TRANSFER-SERVICE
          predicates:
            - Path=/transfer/**

